const INCREMENT = "INCREMENT";
const DECREMENT = "DECREMENT";
const INCREMENT_ASYNC = "INCREMENT_ASYNC";
const INCREMENT_SUCCESS = "INCREMENT_SUCCESS";

export {
    INCREMENT,
    DECREMENT,
    INCREMENT_ASYNC,
    INCREMENT_SUCCESS,
}